[workspace]
members = ["crates/*", "bitwarden_license/*", "tools/*"]
default-members = ["crates/*", "bitwarden_license/*"]
resolver = "3"

[workspace.dependencies]
async-trait = "0.1.89"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4", "serde"] }

bitwarden-auth = { git = "https://github.com/bitwarden/sdk-internal", rev = "e352a06cdfc9e179b21d4b7b502b545fcc68b341" }
bitwarden-collections = { git = "https://github.com/bitwarden/sdk-internal", rev = "e352a06cdfc9e179b21d4b7b502b545fcc68b341" }
bitwarden-core = { git = "https://github.com/bitwarden/sdk-internal", rev = "e352a06cdfc9e179b21d4b7b502b545fcc68b341" }
bitwarden-crypto = { git = "https://github.com/bitwarden/sdk-internal", rev = "e352a06cdfc9e179b21d4b7b502b545fcc68b341" }
bitwarden-pm = { git = "https://github.com/bitwarden/sdk-internal", rev = "e352a06cdfc9e179b21d4b7b502b545fcc68b341" }
bitwarden-state = { git = "https://github.com/bitwarden/sdk-internal", rev = "e352a06cdfc9e179b21d4b7b502b545fcc68b341" }
bitwarden-vault = { git = "https://github.com/bitwarden/sdk-internal", rev = "e352a06cdfc9e179b21d4b7b502b545fcc68b341" }

iced = { git = "https://github.com/iced-rs/iced", rev = "ac1b2c7123ad82643482c0b3a4a776246c966697", default-features = false }

# Compile all dependencies with some optimizations when building this crate on debug
# This slows down clean builds by about 50%, but the resulting binaries can be orders of magnitude faster
# As clean builds won't occur very often, this won't slow down the development process
[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
strip = "debuginfo"
# `lto = "fat"` trims another ~5% but roughly doubles link time.
lto = "thin"
# ~30% smaller binary. But worse performance when not using GPU acceleration.
# opt-level = "z"
# ~20% smaller binary, but turns every `std::panic::catch_unwind` into a hard process abort.
# panic = "abort"

# Enable optimization for the bitwarden-crypto crate. This will increase the binary size slightly (~0.1MB),
# but it will more aggressively inline functions. This will help us avoid extra stack copies of keys and
# other sensitive values being left behind without cleanup.
[profile.release.package.bitwarden-crypto]
opt-level = 3
