[package]
name = "bitwarden-desktop-next"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE.txt"

[dependencies]
async-trait = { workspace = true }
iced = { version = "0.14", features = ["tokio", "svg", "advanced", "image"] }
iced_aw = { version = "0.13", default-features = false }
image = "0.25"
muda = "0.17.1"
serde = { workspace = true }
serde_json = { workspace = true }
system-theme = "0.3.0"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

bitwarden-core = { workspace = true }
bitwarden-crypto = { workspace = true }
bitwarden-pm = { workspace = true }
bitwarden-state = { workspace = true }
bitwarden-vault = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
